apiVersion: v1
kind: ServiceAccount
metadata:
  name: aditi-agent-sa
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: k8s-reader
  namespace: default
rules:
# Pods
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list", "watch"]

# Pod logs (subresource)
- apiGroups: [""]
  resources: ["pods/log"]
  verbs: ["get"]

# Nodes
- apiGroups: [""]
  resources: ["nodes"]
  verbs: ["get", "list", "watch"]

# Deployments
- apiGroups: ["apps"]
  resources: ["deployments"]
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: read-k8s-binding
  namespace: default
subjects:
- kind: ServiceAccount
  name: aditi-agent-sa
  namespace: default
roleRef:
  kind: Role
  name: k8s-reader
  apiGroup: rbac.authorization.k8s.io
